# Generated by Django 4.0.2 on 2022-08-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pironapp', '0004_exampleimagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleImageModel',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/%H:%M:%S.jpg'),
        ),
    ]
